server {
  listen 3001;
  server_name _;
  client_max_body_size 10m;

  location /rest/v1/ {
    proxy_pass http://postgrest:3000/;
    proxy_http_version 1.1;
    proxy_set_header Authorization "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
